package com.jdpmc.jwatcherapp.utils;

public interface Constants {
    String MENU_TITLE = "menu_title";
    String BASE_URL = "https://nispsas.com.ng/";
    String REGISTER_USER_BASE_URL = "https://j-watcher.org/";
    String RECENT_POST_URL = "https://j-watcher.org/";
    String CONFIRM_ACC_BASE_URL = "https://j-watcher.org/";
    String USER_LIKE_BASE_URL = "https://j-watcher.org/";
    String USER_COMMENT_BASE_URL = "https://j-watcher.org/";
    String Reg_School = "https://nispsas.com.ng/PCAS/Mobile/";
    String USERNAME = "username";
    String START1 = "rate1";
    String START2 = "rate2";
    String START3 = "rate3";
    String START4 = "rate4";
    String START5 = "rate5";
    String ACC_STATUS = "account";
    String USERTOWN = "town";
    String USERLGA = "lga";
    String PHONE_NUMBER = "phone_number";
    String CLEAR_A_NOTICE = "notice_clea";
    String USER_IMAGE = "postPath";
    String SPLASH_SCREEN = "splash_screen";
    String LATITUDE = "latitude";
    String LONGITUDE = "longitude";
    String VERIFY_DRIVER_BASE_URL = "http://35.162.169.102/";
    String UPLOAD_MEDIA_BASE_URL = "http://tocnetng.com.ng/";
    String VERIFY_BASE_URL = "http://nispsas.org.ng/NISPSAS/Gateway/";
    String NOTIFICATION_BASE_URL = "https://j-watcher.org/Apps/Mobile/";
    String VIDEO_PLAYER_BASE_URL = "https://j-watcher.org/Apps/Mobile/";
    String GET_HOT_URL = "https://j-watcher.org/Apps/Mobile/";
    String GET_USEFUL_URL = "https://j-watcher.org/Apps/Mobile/";
    String ALL_REGISTRATION = "https://nispsas.com.ng/NISPSAS/Registration/LoadTrad";
    String EAAP = "https://nispsas.com.ng/NISPSAS/Registration/LoadHouse";
    String EDUCATE ="https://nispsas.com.ng/NISPSAS/Registration/LoadEdu";
    String TERMS = "terms";
    String FACE_VERIFY ="http://nispsas.com.ng/NISPSAS/Registration";
    String FIREBASE_TOKEN = "firebasekey";
    String RESOURCE_URI = "resource_uri";
    String LGA = "lga";
    String PUnit = "punit";
    String STATE = "state";
}
